language: node_js

# Keep empty to use version from .nvmrc
node_js: null

install:
  - npm ci

script:
  - npm run lint
  - npx semantic-release

branches:
  only:
    - master

notifications:
  email: false
