language: node_js
node_js:
  - '7'
  - '6'
  - '5'
  - '4'

cache:
  directories:
  - node_modules

script:
  - npm test

branches:
  only:
    - master

notifications:
  slack:
    rooms:
      secure: gWUSd2Bz93TrjovT9tSVV0zZRQ61xvU4IiE7FoZpKNM4jfCwj3wEmw2duF4ytCewxty7MKV5wb/Ci8vOaSQF5kf4n9f2v8XCa71Iqjm/yHRqc7p8hxo2r/JYmWEDaoYMhFqNFMlCP/ZHk1p6qPuweJMl6UktNGsjoit32ZZuPR9ATkdbGFErtMPjVG+Ww+MYWLlpnyZhVaYg9UAwTc8YOhtx7y895YPIKGJ9FO6H2nUGjTVwobmCVvzbqhfg8o+9wPFuUJ0ekSW1+ijxiHDH6DMEnhGk6VA2SXD/wdN0Zsgm+XCeclAO52zdDiqLwXHflSTLLYgh0Mb6Xt+mhLY+GBU3NEH93jVEvVH4X5xOGctZpG36sgQCDCAA887bzBvJVFstmlOsFzVAa+VsYHWK3EjBZ264KFdeHwnpZE5ExdQk5eqdZaOVwtnlFtqObc0sZCR4wzPaHEmsVsa7YKncaDJ1IPCJaYUxHUVj6ZcD0Z0TTw/AzX/4gyO2yRGm2CYe53dNqqXSoCutb0q/6bJ1/94k4U/zewviJ/BT2EQZ1fRKnDRpDtaJRkrB2neNab/XtrZuVz73MU5DcnwK6NjBgEo+6smFh34n68JQZpFJoKCchqcL3eWT2HJ8dl1DtRyC+zY4reELwBa8Cggq/x4SL8P4baFEjgwM0UxLVOf+pqg=
    on_success: never
    on_failure: always
    on_start: never
